<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>elementWithAttribute</name>
   <tag></tag>
   <elementGuidId>40b3e4a9-458c-41ec-bebf-905096f84265</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body//${value1}[@${value2}='${value3}']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
