<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>objectText</name>
   <tag></tag>
   <elementGuidId>468c68de-fcb7-47d9-a609-73c32396a41c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>*//*[text()='${value1}']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
