<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>objectName</name>
   <tag></tag>
   <elementGuidId>bd0e14ac-776d-40eb-b4dd-e9c2d53df015</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>*//*[@Name='${value1}']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
